# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'number1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_demobox(object):
    def setupUi(self, demobox):
        demobox.setObjectName("demobox")
        demobox.setWindowModality(QtCore.Qt.ApplicationModal)
        demobox.resize(320, 240)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../media/ursia/16EC8BACEC8B84A9/Users/ursia/Pictures/clients/logozekin4perso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        demobox.setWindowIcon(icon)
        demobox.setWindowOpacity(10.0)
        demobox.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(demobox)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(45, 30, 241, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("border-top-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"background-color: rgb(117, 80, 123);")
        self.comboBox.setEditable(False)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["c", "c++", "c#", "java", "python", "python3"])
        self.comboBox.currentIndexChanged.connect(selectedchanged)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(47, 100, 241, 26))
        self.spinBox.setObjectName("spinBox")
        self.spinBox.valueChanged.connect(valueChan)
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setEnabled(False)
        self.label_1.setGeometry(QtCore.QRect(110, 70, 111, 17))
        self.label_1.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label_1.setObjectName("label_1")
        demobox.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(demobox)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 22))
        self.menubar.setObjectName("menubar")
        demobox.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(demobox)
        self.statusbar.setObjectName("statusbar")
        demobox.setStatusBar(self.statusbar)
        self.label_1.setBuddy(self.spinBox)

        self.retranslateUi(demobox)
       self.spinBox.valueChanged['int'].connect(self.label_1.setNum)# type: ignore
        QtCore.QMetaObject.connectSlotsByName(demobox)

    def retranslateUi(self, demobox):
        _translate = QtCore.QCoreApplication.translate
        demobox.setWindowTitle(_translate("demobox", "combo/SpinBox box demo"))
        self.comboBox.setProperty("addItems", _translate("demobox", "c\n"
"c++\n"
"c#\n"
"python\n"
"java"))
    
        



def selectedchanged(comboBox):
    print("item in the list are: ")


    for i in range(comboBox):
        print (i)
        

def valueChan(spinBox):
    i = str(spinBox) 
    print(i)
   



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    demobox = QtWidgets.QMainWindow()
    ui = Ui_demobox()
    ui.setupUi(demobox)
    demobox.show()
    sys.exit(app.exec_())
