# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'number4.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.setWindowModality(QtCore.Qt.ApplicationModal)
        TabWidget.resize(400, 361)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TabWidget.sizePolicy().hasHeightForWidth())
        TabWidget.setSizePolicy(sizePolicy)
        TabWidget.setMaximumSize(QtCore.QSize(400, 500))
        TabWidget.setWindowOpacity(62.0)
        TabWidget.setAutoFillBackground(False)
        TabWidget.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"gridline-color: rgb(245, 121, 0);\n"
"border-radius: solid, black, 0.7;")
        TabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        TabWidget.setDocumentMode(True)
        TabWidget.setTabsClosable(True)
        
        loadata(TabWidget)

        self.retranslateUi(TabWidget)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))


def loadata(TabWidget):
    connection = sqlite3.connect("database.db")
    cursor = connection.cursor()

    rows = cursor.execute("SELECT id, name, firstname, age FROM person").fetchall()
    print(rows)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())
